name: CMake on Ubuntu

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - uses: actions/checkout@v2

      - run: cmake --workflow --preset ci
